### ISSUE TITLE
Not possible add a class without the namespace?

### ISSUE THREAD

**Issue by paveleremin** [ClassPreloader/ClassPreloader#29]
PHP Fatal error: Cannot mix bracketed namespace declarations with unbracketed namespace declarations in /var/www/laravel.local/bootstrap/compiled.php on line 10906

**Comment by paveleremin** [comment]
@GrahamCampbell hi! No, my problem still actual with using Laravel 4.2

**Comment by GrahamCampbell** [comment]
Yeh, laravel is using an old version of clasd preloader. I'm hoping to get L5 to ship with the latest version.

**Comment by GrahamCampbell** [comment]
@paveleremin Ok, https://github.com/laravel/framework/pull/7049 just got merged so now lararavel 5 uses the very latest version of super closure. Is your issue fixed now?

**Comment by GrahamCampbell** [comment]
This has been fixed now. :)
