### ISSUE TITLE
packagist Version 1.0.2 points to wrong git repo

### ISSUE THREAD

**Issue by cocoanton** [ClassPreloader/ClassPreloader#45]
I'm not sure this should be on your table since I'm not that familiar with package-handling.

When deploying Laravel 4.2 to Heroku I noticed that composer is trying to pull ClassPreloader from https://github.com/mtdowling/ClassPreloader.git

This is usually not a problem since composer fails to download the zip it downloads it from the source. However, Heroku seems not to follow the redirect from mtdowling/ClassPreloader to ClassPreloader/ClassPreloader and fails installing and ends the deployment.

The solution for me was to change the composer.lock-file to the correct repo. 

Is it an good idea, or even possible to change the repository urls in older versions of ClassPreloader? 
The references still works since they are the same, it's just the zip-url and git-urls.

Snippet from heroku's failed install attempt.
```
- Installing classpreloader/classpreloader (1.0.2)
           Downloading: connection...
           Failed to download classpreloader/classpreloader from dist: The "https://api.github.com/repos/mtdowling/ClassPreloader/zipball/2c9f3bcbab329570c57339895bd11b5dd3b00877" file could not be downloaded (HTTP/1.1 404 Not Found)
           Now trying to download from source
         - Installing classpreloader/classpreloader (1.0.2)
           Cloning 2c9f3bcbab329570c57339895bd11b5dd3b00877
       
       
                                                                                                               
         [RuntimeException]                                                                                    
         Failed to clone git@github.com:mtdowling/ClassPreloader.git via git, https, ssh protocols, aborting.  
                                                                                                               
         - git://github.com/mtdowling/ClassPreloader.git                                                       
           fatal: Not a git repository: '.'                                                                    
                                                                                                               
         - https://github.com/mtdowling/ClassPreloader.git                                                     
           fatal: Not a git repository: '.'                                                                    
                                                                                                               
         - git@github.com:mtdowling/ClassPreloader.git                                                         
           Host key verification failed.                                                                       
           fatal: The remote end hung up unexpectedly       
```

**Comment by GrahamCampbell** [comment]
You need to clear your composer cache. This is an issue with composer, sorry.

**Comment by cocoanton** [comment]
But I did, this was a clean install with no cache, the cached version worked fine on staging and locally, but not when doing a clean install on a new system. I can however see that this is an composer issue.

**Comment by richardchim** [comment]
I just ran into this as well. To get past it, I just updated the composer.lock file via "composer update" (updates everything). Then I pushed the lock file back into my repo and that did the trick.
