### ISSUE TITLE
[PHP 7] Yet another interesting error

### ISSUE THREAD

**Issue by shehi** [ClassPreloader/ClassPreloader#46]
![image](https://cloud.githubusercontent.com/assets/653569/7154400/6c2d634e-e35e-11e4-9f1e-aa62075093d4.png)

**Comment by shehi** [comment]
This package is required by ```laravel/framework```. But Laravel itself successfully runs its own tests - guess because Laravel actually doesn't use RDBMS in tests. Should I create PR and rename that namespace alias?

**Comment by GrahamCampbell** [comment]
Yeh, this is a known issue.

> Should I create PR and rename that namespace alias?

No. That still would break on php 7.

**Comment by GrahamCampbell** [comment]
I'll fix this myself shortly. I already know what's causing it and how to get this sorted. Just haven't found the time yet.

**Comment by shehi** [comment]
Ok then. Feel free to close this issue when done then :)

**Comment by GrahamCampbell** [comment]
Done. :)

**Comment by GrahamCampbell** [comment]
This should be available as `1.3.*@dev`, or by just lowering your minimum stability to dev in your main composer.json for your laravel app.

**Comment by GrahamCampbell** [comment]
If there are no issues, I'll release 1.3.0 soon.
