### ISSUE TITLE
Classes without namespace

### ISSUE THREAD

**Issue by KennedyTedesco** [ClassPreloader/ClassPreloader#48]
I'm having the same problem as https://github.com/ClassPreloader/ClassPreloader/issues/29

Follow this steps:

**compiled.php**
```php
<?php
namespace Illuminate\Contracts\Container;

use Closure;

interface Container
{
    public function bound($abstract);
    public function alias($abstract, $alias);
}

namespace MyApp\Foo;

class MyClass
{
    public function doSomething()
    {

    }
}

namespace {
    class MyClass
    {
        public function doSomething()
        {

        }
    }
}
```

My test file:

**index.php**
```php
<?php

require "compiled.php";

$class = new MyApp\Foo\MyClass();
var_dump($class);

$class2 = new MyClass();
var_dump($class2);
```

Throws this error:

```
Fatal error: Cannot mix bracketed namespace declarations with unbracketed namespace declarations in /Users/kennedytedesco/Documents/www/compiled.php on line 22
```

But if I change my **compiled.php** file to have just bracketed namespaces:

```php
<?php
namespace Illuminate\Contracts\Container {
    use Closure;

    interface Container
    {
        public function bound($abstract);
        public function alias($abstract, $alias);
    }
}

namespace MyApp\Foo {
    class MyClass
    {
        public function doSomething()
        {

        }
    }
}

namespace {
    class MyClass
    {
        public function doSomething()
        {

        }
    }
}
```

Works fine:

```php
object(MyApp\Foo\MyClass)#1 (0) { } 
object(MyClass)#2 (0) { }
```

I'm working with php 5.6.9.

```
PHP 5.6.9 (cli) (built: May 15 2015 21:32:02) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
```

This PR https://github.com/ClassPreloader/ClassPreloader/pull/25 need to be merged, or, another option is add brackets to all namespaces, like shown before.

**Comment by GrahamCampbell** [comment]
Please don't create another issue for an existing issue.

**Comment by GrahamCampbell** [comment]
Is there any chance you could take up that existing PR since I can't merge it in its current state?

**Comment by GrahamCampbell** [comment]
I would merge it if it actually worked and didn't have merge conflicts. :)

**Comment by KennedyTedesco** [comment]
@GrahamCampbell I can send a new PR if you want to.

But the main question is:

```php
<?php
namespace Illuminate\Contracts\Container;

use Closure;

interface Container
{
    public function bound($abstract);
    public function alias($abstract, $alias);
}

namespace MyApp\Foo;

class MyClass
{
    public function doSomething()
    {

    }
}

namespace {
    class MyClass
    {
        public function doSomething()
        {

        }
    }
}
```

This approach works in which version of PHP? Do you know? We need to know before we step forward with this PR.

**Comment by GrahamCampbell** [comment]
> This approach works in which version of PHP? Do you know?

Sorry, not sure. You could try creating a test case for it in our test suite, then get travis to run it.

**Comment by GrahamCampbell** [comment]
> I can send a new PR if you want to.

That would be wonderful if you can. :)
