### ISSUE TITLE
[2.0] Plans For The Next Major Version

### ISSUE THREAD

**Issue by GrahamCampbell** [ClassPreloader/ClassPreloader#50]
I want this to work better as a library. I plan to move the symfony console stuff into a new package, and have this stuff work as a stand-alone library. I also plan to drop support for php 5.3 and php 5.4. We will be php 5.5.9+ from 2.0 onwards. I plan to keep 1.x maintained for a good amount of time too.

**Comment by KennedyTedesco** [comment]
That's great. :+1:
