### ISSUE TITLE
What is wrong? PHP Fatal error:  Class 'ClassPreloader\Application' not found

### ISSUE THREAD

**Issue by seyfer** [ClassPreloader/ClassPreloader#52]
```
php vendor/bin/classpreloader.php compile --config="public/preloaderConfig.php" --output="public/preloader.php"
PHP Fatal error:  Class 'ClassPreloader\Application' not found in /home/.../vendor/classpreloader/console/classpreloader.php on line 20

```

**Comment by GrahamCampbell** [comment]
Probably because you've updated to 2.0?

**Comment by GrahamCampbell** [comment]
All the console support was removed and moved to a different repo.

**Comment by seyfer** [comment]
Why instructions not updated ? How to install it right ?

I used this

```
"classpreloader/classpreloader": "^2.0"
"classpreloader/console": "^1.0"
```

Look at my pool. There is fix
https://github.com/ClassPreloader/Console/pull/1

**Comment by seyfer** [comment]
Please, merge and tag 1.0.1 version or whatever for update.

**Comment by GrahamCampbell** [comment]
Thanks for your PR. I've reverted your change to the .gitignore file though. The `.idea` thing belongs in your global level ignore file.

**Comment by GrahamCampbell** [comment]
I'll tag a release as soon as I can. My laptop is currently broken.

**Comment by seyfer** [comment]
Thank you. I will waiting.
