### ISSUE TITLE
How to generate with include only?

### ISSUE THREAD

**Issue by seyfer** [ClassPreloader/ClassPreloader#53]
Hi

I'm using cli tool like this

```
php classpreloader.php compile --config="preloaderConfig.php" --output="public/preloader.php"
```

here is my config
```
ini_set('display_errors', 0);
require 'vendor/classpreloader/classpreloader/src/ClassLoader.php';

use ClassPreloader\ClassLoader;

$config = ClassLoader::getIncludes(function (ClassLoader $loader) {
    require 'vendor/autoload.php';
    $loader->register();

    include_once "public/spot/code.php";
});

// Add a regex filter that requires all classes to match the regex
// $config->addInclusiveFilter('/Foo/');

// Add a regex filter that requires that a class does not match the filter
// $config->addExclusiveFilter('/Foo/');

return $config;
```

All code with all calls in file code.php
When I run tool it generates empty preloader.php. Why ?

**Comment by seyfer** [comment]
??? :)

**Comment by GrahamCampbell** [comment]
Which version are you using?

**Comment by GrahamCampbell** [comment]
> require 'vendor/classpreloader/classpreloader/src/ClassLoader.php';

You shouldn't need to do that because the cli script should autoload that.

**Comment by seyfer** [comment]
I'm using 2.0 version. You know that from my another issue and recent pull request that you merged. :)

**Comment by GrahamCampbell** [comment]
Sorry, It's hard to keep track of people I talk to on GitHub. I treated this issue as a totally fresh scenario.
