### ISSUE TITLE
Specific use case?

### ISSUE THREAD

**Issue by haphan** [ClassPreloader/ClassPreloader#57]
Right now I cannot think of any specific use case. Can you give an example?

Cheers.

**Comment by GrahamCampbell** [comment]
You can compile files that are loaded on every web request on your server for example.

**Comment by GrahamCampbell** [comment]
Laravel does this.

**Comment by haphan** [comment]
1. PHP already has OpCache for this purpose. Constantly amending cache file in fact making OpCache less useful (need to refresh cache all the time). Production servers, for example, even disable timestamp validation for OpCache.
2. Linux kernel also has IO cache for frequently read files.
3. Laravel does this does not mean it is a good practice.

Did you attempt to set-up any benchmark for a specified use-case you found useful?

**Comment by GrahamCampbell** [comment]
> Did you attempt to set-up any benchmark for a specified use-case you found useful?

Yes, on PHP 5, the results were actually very significant. Anywhere between 1.5 and 3 times load time improvement.

**Comment by GrahamCampbell** [comment]
On PHP 7, the results are much less significant.
