### ISSUE TITLE
Cannot instantiate interface PhpParser\Parser

### ISSUE THREAD

**Issue by Awesomez** [ClassPreloader/ClassPreloader#58]
in ClassPreloader/src/Factory.php file line 64 , I find this code   return new Parser(new Lexer()) , but the Parser is interface in the nikic/php-parser/lib/PhpParser/Parser.php , so I think it is a bug because we cant new a interface.

**Comment by GrahamCampbell** [comment]
Hmm, thanks for the report. I'll investigate.

**Comment by GrahamCampbell** [comment]
I've just run the test suite on my machine using php parser 1.x and then 2.x, and I can't replicate this issue?

**Comment by GrahamCampbell** [comment]
Like 64 is only run on php parser 1.x, because the factory class is present on 2.x, so we never execute line 64 on 2.x.

**Comment by GrahamCampbell** [comment]
Please let me know if you are experiencing any issues actually running the code. I assume you caught this  using a static analyser in your IDE?

**Comment by Awesomez** [comment]
thanks for reply ! I know the reason, because my parser is too old so it  execute line 64 . but it is still a "bug" here although it not be executed ^_^

**Comment by GrahamCampbell** [comment]
We support the old version too?

**Comment by GrahamCampbell** [comment]
What actual version of php parser do you ave?

**Comment by Awesomez** [comment]
Haha we don't need to support the old version . My parser version is 2.0.2-dev and there is no parser factory here.  IDE always tell me that a bug is here although it not be executed  after updating the parser to last version.

**Comment by Awesomez** [comment]
I read the Parser change log and find the parser factory had been added in version 2.0.0-alpha1. Maybe there is something wrong with my code which lost the factory class .
