### ISSUE TITLE
Allow use with php parser 4.x too

### ISSUE THREAD

**Issue by SidIcarus** [ClassPreloader/ClassPreloader#65]

**Comment by GrahamCampbell** [comment]
Out of interested, what is your use case for this package please?

**Comment by SidIcarus** [comment]
Hey,

I'm using `flipbox/lumen-generator` which depends on this package. Several QA-related tools don't have as great of a supported range so I'm resolving the conflict with an inline alias, as shown below.
```
each requires nikic/php-parser
me                                        (4.2.1 as 3.2) 
classpreloader/classpreloader     3.2.0   (^1.0|^2.0|^3.0)
maglnet/composer-require-checker  2.0.0   (^4.0)
phpmetrics/phpmetrics             v2.4.1  (^3|^4)
phpstan/phpstan                   0.11.6  (^4.0.2)
povils/phpmnd                     v2.1.0  (^4.0)
psy/psysh                         v0.9.9  (~1.3|~2.0|~3.0|~4.0)
vimeo/psalm                       3.2.12  (^4.0.2 || ^4.1)
```

I figured since this packages code has been quite stable for sometime then the code it depends on in the parser has also been quite stable. So, this request for a greater version range seemed reasonable.

**Comment by GrahamCampbell** [comment]
Thanks for the details. :)

I'll look at what we need to do to support the 4.x series.

**Comment by Lohn** [comment]
Exactly the same problem here. And I can't install phpdox because of this.

**Comment by GrahamCampbell** [comment]
Thanks for the feedback. I'm going to look at getting this package upgraded within the next few days. :)

**Comment by GrahamCampbell** [comment]
Sorry for the delay here. I am still planning to get to this ASAP.

**Comment by GrahamCampbell** [comment]
Support for PHP Parser 4 will be released today. 🚀

**Comment by GrahamCampbell** [comment]
I've submitted a PR to the library to allow it to support both v3 and v4: https://github.com/flipboxstudio/lumen-generator/pull/68.
